# config/api_config.yaml  
# OLLAMA_CONTEXT_LENGTH=8192 ollama serve

embedding_model:
  model: "nomic-embed-text:latest"

evaluate_model:
  model: "glm4:latest"
  # model: "gemma3:12b"
  # model: "phi4:latest"
  # model: "qwen2.5:14b"